#!/bin/sh
echo "Making initial commit..."
git init
git add --all
echo "Adding ops subtree."
git commit --author="Cookiecutter (JonathanPorta/cookiecutter-lambda-nodets-template) - <jonathan@jonathanporta.com>" -m "Initial Commit - Generated by https://github.com/JonathanPorta/cookiecutter-lambda-nodets-template"
git remote add ops git@github.com:jonathanporta/common-ops.git --no-tags
git subtree add --prefix ops/ ops master --squash
echo "Project generated."
cp ./.env-sample ./.env
echo "Please update your .env file with your environment variables."
